# Generated by Django 3.2.3 on 2021-05-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_no', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('phone_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('labor_time', models.DurationField()),
                ('cost', models.FloatField(default=0.0)),
                ('name', models.CharField(db_index=True, max_length=60, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PART', 'Part'), ('TEST', 'Test')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('appt_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.TimeField(db_index=True)),
                ('dropoff_time', models.TimeField(null=True)),
                ('pickup_time', models.TimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='served_customer', to='car_dealer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('car_age', models.IntegerField(null=True)),
                ('service_names', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('model', models.CharField(db_index=True, max_length=60)),
                ('make', models.CharField(db_index=True, max_length=60)),
                ('msrp', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePerformed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='appt_for_service', to='car_dealer.serviceappointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_for_appt', to='car_dealer.service')),
            ],
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='service_package',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_package', to='car_dealer.servicepackage'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='served_vehicle', to='car_dealer.vehicle'),
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('date', models.DateField(auto_now=True, db_index=True)),
                ('price', models.IntegerField()),
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_customer', to='car_dealer.customer')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchased_vehicle', to='car_dealer.vehicle')),
            ],
        ),
    ]
