# Generated by Django 3.1.2 on 2021-05-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='purchasebill',
            table='purchase_bill',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='serviceappointment',
            table='service_appointment',
        ),
        migrations.AlterModelTable(
            name='servicepackage',
            table='service_package',
        ),
        migrations.AlterModelTable(
            name='serviceperformed',
            table='service_performed',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
