# Generated by Django 3.1.2 on 2021-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0002_auto_20210515_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='dropoff_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='pickup_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
